name: Auto push to GitHub Page branch
on:
  push:
    branches:
      - main
    paths:
      - docs/**
jobs:
  gen_dict:
    name: Generate schemas dictionary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Export
        shell: pwsh
        run: . "./schema_file_g.ps1"
      - name: Commit dictionary data
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "enquiry@rk0cc.xyz"
          git commit -am "Genrate dictionary file"
      - name: Push commited
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: gen_dict
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Merge
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: gh-page
          github_token: ${{ github.token }}
