name: Auto push to GitHub Page branch
on:
  workflow_run:
    workflows:
      - Generate schema dictionary
    types:
      - completed
    branch:
      - main
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Merge
        uses: devmasx/merge-branch@1.4.0
        continue-on-error: true
        with:
          type: now
          target_branch: gh-page
          github_token: ${{ github.token }}
